trigger:
  batch: true
  branches: 
    include:
    - master

name: $(date:yyyy-MM-dd)_$(rev:.r)

pool:
  vmImage: 'Ubuntu-20.04'

variables:
  registryName: 'nozzlegear.azurecr.io'
  repositoryName: 'discord-dynamic-voice-channels'
  baseImageName: '$(registryName)/$(repositoryName)'
  latestImageName: '$(baseImageName):latest'
  buildImageName: '$(baseImageName):$(build.buildId)'

steps:
- task: Docker@2
  displayName: Login to Azure Container Registry
  inputs:
    command: login
    containerRegistry: 'Nozzlegear ACR connection'

- task: Docker@2
  displayName: 'Build and push container image'
  inputs:
    command: buildAndPush
    repository: $(repositoryName)
    tags: |
      $(latestImageName)
      $(buildImageName)
