name: Build Pipeline

on:
  push:
    branches: [ $default-branch, actions-test ]

env:
  BUILD_IMAGE_NAME: "${{ secrets.ACR_REGISTRY }}/discord-dynamic-voice-channels:${{ github.run_number }}"
  LATEST_IMAGE_NAME: "${{ secrets.ACR_REGISTRY }}/discord-dynamic-voice-channels:latest"

jobs:
  build:
    name: "Build and push"
    runs-on: ubuntu-20.04
    environment: "Build Environment"

    steps:
    - name: Log in to Azure Container Registry
      env:
        ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      run: echo "$ACR_PASSWORD" | docker login --password-stdin --username "$ACR_USERNAME" "$ACR_REGISTRY"

    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Build container image
      run: docker build -t "$BUILD_IMAGE_NAME" -t "$LATEST_IMAGE_NAME" .

    - name: Push container image
      run: docker push "$BUILD_IMAGE_NAME" && docker push "$LATEST_IMAGE_NAME"

  deploy:
    name: "Deploy to Cryptum"
    runs-on: ubuntu-20.04
    environment: "Cryptum Deployment Environment"
    # Do not run this job until the build job completes
    needs: build

    steps:
    - name: Checkout branch
      uses: actions/checkout@master

    - name: Copy deployment script to Cryptum
      uses: appleboy/scp-action@master
      with:
        key: ${{ secrets.CRYPTUM_PRIVATE_KEY }}
        host: ${{ secrets.CRYPTUM_HOST }}
        username: ${{ secrets.CRYPTUM_USERNAME }}
        passphrase: ${{ secrets.CRYPTUM_SSH_PASSPHRASE }}
        # Use a host fingerprint to ensure we always connect to the same server
        #fingerprint: ${{ secrets.CRYPTUM_HOST_FINGERPRINT }}
        source: ".github/scripts/cryptum-deployment.sh"
        target: "/etc/deployments/cryptum-deployment.sh"
        overwrite: true

    - name: Execute deployment script via SSH
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.CRYPTUM_PRIVATE_KEY }}
        host: ${{ secrets.CRYPTUM_HOST }}
        username: ${{ secrets.CRYPTUM_USERNAME }}
        passphrase: ${{ secrets.CRYPTUM_SSH_PASSPHRASE }}
        #fingerprint: ${{ secrets.CRYPTUM_HOST_FINGERPRINT }}
        # Stop on errors
        script_stop: true
        script: bash -C "/etc/deployments/cryptum-deployment.sh" "$BUILD_IMAGE_NAME"
