name: Build Pipeline

on:
  push:
    branches: [ $default-branch, actions-test ]

env:
  BUILD_IMAGE_NAME: "${{ secrets.ACR_REGISTRY }}/discord-dynamic-voice-channels:${{ github.run_number }}"
  LATEST_IMAGE_NAME: "${{ secrets.ACR_REGISTRY }}/discord-dynamic-voice-channels:latest"

jobs:
  build:
    name: "Build and push"
    runs-on: ubuntu-20.04
    environment: "Build Environment"

    steps:
    - name: Log in to Azure Container Registry
      env:
        ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      run: echo "$ACR_PASSWORD" | docker login --password-stdin --username "$ACR_USERNAME" "$ACR_REGISTRY"

    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Build container image
      run: docker build -t "$BUILD_IMAGE_NAME" -t "$LATEST_IMAGE_NAME" .

    - name: Push container image
      run: docker push "$BUILD_IMAGE_NAME" && docker push "$LATEST_IMAGE_NAME"
